export const products = [{
        uid: 1,
        marca: 'Ejemplo1',
        subcategoria: 'Subcategoría1',
        categoria: 'Categoría1',
        precio: 10.0,
        descripcion: 'Descripción del producto 1',
        foto: 'https://estudiokobe.com/wp-content/uploads/Fotografia-de-producto-buenos-aires-argentina-zapatos-calzado-femenino-e-commerce-7-1-768x680.jpg',
        stock: 100,
        photoUrl: '',
    },
    {
        uid: 2,
        marca: 'Ejemplo2',
        subcategoria: 'Subcategoría2',
        categoria: 'Categoría2',
        precio: 20.0,
        descripcion: 'Descripción del producto 2',
        foto: 'https://estudiokobe.com/wp-content/uploads/fotografia-de-producto-argentina-accesorios-carteras-2-1-768x768.jpg',
        stock: 200,
        photoUrl: '',
    },
    {
        uid: 3,
        marca: 'Ejemplo3',
        subcategoria: 'Subcategoría3',
        categoria: 'Categoría3',
        precio: 20.0,
        descripcion: 'Descripción del producto 2',
        foto: 'https://img.global.news.samsung.com/ar/wp-content/uploads/2023/01/Samsung_New_Screens_dl2-845x563.jpg',
        stock: 200,
        photoUrl: '',
    },
]